apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "python"
  replicas: 6
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: cloudsiksha/pythonapp:v1
        ports:
        - containerPort: 80
          name: web
        

